import test from 'node:test'
import assert from 'node:assert/strict'
import { buildCoachRecommendation } from '../src/core/coachIntelligenceEngine.js'

const now = new Date('2026-07-21T12:00:00Z').getTime()
function baseState() { return { profile: { name: 'Robert Ekholm' }, workouts: [{ id: 'w1', name: 'Pull', completedAt: '2026-07-15T18:00:00Z', sets: 16, exercises: [] }, { id: 'w2', name: 'Push', completedAt: '2026-07-18T18:00:00Z', sets: 14, exercises: [] }, { id: 'w3', name: 'Legs', completedAt: '2026-07-20T18:00:00Z', sets: 12, exercises: [] }], recovery: { score: 84, muscles: { Rygg: { fatigue: 8, updatedAt: '2026-07-20T00:00:00Z' }, Ben: { fatigue: 45, updatedAt: '2026-07-20T00:00:00Z' } } }, decisions: { current: { id: 'd1', category: 'training', action: 'train', title: 'Rygg är redo för kvalitetsträning', message: 'Rygg har högst beräknad återhämtning.', evidence: ['Rygg: 92% återhämtad', 'Total återhämtning: 84%'] } }, goals: [{ id: 'g1', title: 'Thailand', target: 'Bättre form', weeks: 8, progress: 50 }], goalPlans: { active: { title: 'Thailand', target: 'Bättre form', alerts: [], progress: 50 } }, memory: { generatedAt: '2026-07-21T11:00:00Z', memories: [{ id: 'm1', title: 'Pull är återkommande', detail: '3 pass', confidence: .8 }] }, predictions: { generatedAt: '2026-07-21T11:00:00Z', items: [{ id: 'p1', status: 'active', category: 'training', title: 'Estimated consistency forecast', description: 'Frequency stable.', recommendation: 'Du behåller nuvarande träningsfrekvens.', confidence: .72 }] }, coach: { insights: [{ id: 'i1', title: 'Jämn rytm', detail: 'Du svarar bra på jämn träningsrytm.', confidence: .9 }] } } }

test('high-confidence training recommendation', () => { const rec = buildCoachRecommendation(baseState(), now); assert.equal(rec.primaryActionTarget, 'training'); assert.ok(rec.confidence >= .7); assert.match(rec.primaryActionLabel, /STARTA PASS/) })
test('recovery recommendation', () => { const s = baseState(); s.decisions.current = { id:'r', category:'recovery', action:'reduce-load', title:'Undvik tung belastning för Ben', message:'Ben är lågt återhämtad.', evidence:['Ben: 25% återhämtad'] }; s.recovery.score = 52; s.recovery.muscles.Ben.fatigue = 75; const rec = buildCoachRecommendation(s, now); assert.equal(rec.primaryActionTarget, 'recovery'); assert.equal(rec.primaryActionLabel, 'VÄLJ ÅTERHÄMTNING') })
test('insufficient-data state', () => { const rec = buildCoachRecommendation({ profile: {}, workouts: [], recovery: { muscles: {} }, coach: {} }, now); assert.equal(rec.insufficientData, true); assert.equal(rec.primaryActionLabel, 'LOGGA DAGSFORM') })
test('no fabricated readiness values', () => { const rec = buildCoachRecommendation({ workouts: [], recovery: { muscles: {} }, coach: {} }, now); assert.equal(rec.context.recoveryScore, null); assert.equal(rec.context.latestWorkout, null); assert.equal(rec.dataQuality.signals, 0) })
test('reason ranking', () => { const rec = buildCoachRecommendation(baseState(), now); assert.equal(rec.reasons[0].source, 'decision-engine') })
test('conflicting insight handling deduplicates reasons', () => { const s = baseState(); s.decisions.current.evidence.push('Rygg: 92% återhämtad'); const rec = buildCoachRecommendation(s, now); assert.equal(new Set(rec.reasons.map(r=>r.text)).size, rec.reasons.length) })
test('prediction hidden when confidence is too low', () => { const s = baseState(); s.predictions.items[0].confidence = .2; const rec = buildCoachRecommendation(s, now); assert.equal(rec.expectedImpact, null) })
test('correct primary action selection for modify', () => { const s = baseState(); s.decisions.current.action = 'modify-volume'; const rec = buildCoachRecommendation(s, now); assert.equal(rec.primaryActionLabel, 'JUSTERA DAGENS PASS') })
test('no mutation of input state', () => { const s = baseState(); const before = JSON.stringify(s); buildCoachRecommendation(s, now); assert.equal(JSON.stringify(s), before) })
test('legacy coach-state compatibility shape', () => { const rec = buildCoachRecommendation({ ...baseState(), coach: { memories: [] } }, now); assert.ok(rec.id); assert.ok(Array.isArray(rec.supportingInsights)) })
