const COPY = {
  en: { decisions: { train: 'Ready to train', train_light: 'Train light today', recovery: 'Prioritize recovery', deload: 'Reduce training load', insufficient_data: 'More data is needed' }, rec: { push: 'Push', pull: 'Pull', legs: 'Legs', upper: 'Upper body', lower: 'Lower body', full_body: 'Full body', priority_muscles: 'Priority muscles', recovery: 'Recovery' }, confidence: 'Recommendation confidence', caution: 'Avoid loading recovering or restricted muscles.', quality: { none: 'Log a workout or recovery check-in to unlock a recommendation.', low: 'This recommendation uses limited data.', good: 'This recommendation is based on your current goal and recovery data.' } },
  sv: { decisions: { train: 'Redo att träna', train_light: 'Träna lätt idag', recovery: 'Prioritera återhämtning', deload: 'Minska träningsbelastningen', insufficient_data: 'Mer data behövs' }, rec: { push: 'Press', pull: 'Drag', legs: 'Ben', upper: 'Överkropp', lower: 'Underkropp', full_body: 'Helkropp', priority_muscles: 'Prioriterade muskler', recovery: 'Återhämtning' }, confidence: 'Rekommendationens säkerhet', caution: 'Undvik att belasta återhämtande eller begränsade muskler.', quality: { none: 'Logga ett pass eller en återhämtningskontroll för att få en rekommendation.', low: 'Rekommendationen bygger på begränsad data.', good: 'Rekommendationen bygger på ditt aktuella mål och din återhämtning.' } },
}

export function explainCoachDecision(output = {}, language = 'en') {
  const text = COPY[language === 'sv' ? 'sv' : 'en']
  const confidence = Math.max(0, Math.min(100, Math.round(Number(output.confidence) || 0)))
  const reasons = Array.isArray(output.reasonCodes) ? output.reasonCodes : []
  const points = [reasons.includes('HIGH_READINESS') ? (language === 'sv' ? 'Din registrerade återhämtning stödjer normal belastning.' : 'Your recorded recovery supports normal loading.') : null, reasons.includes('MODERATE_READINESS') ? (language === 'sv' ? 'Din registrerade återhämtning stödjer ett lättare pass.' : 'Your recorded recovery supports a lighter session.') : null, output.focusMuscles?.length ? `${language === 'sv' ? 'Fokus' : 'Focus'}: ${output.focusMuscles.join(', ')}.` : null].filter(Boolean)
  return { headline: text.decisions[output.decision] || text.decisions.insufficient_data, summary: `${text.rec[output.recommendation] || text.rec.recovery} · ${text.confidence} ${confidence}%.`, supportingPoints: points, caution: output.avoidMuscles?.length ? text.caution : '', dataQualityMessage: confidence === 0 ? text.quality.none : confidence < 65 ? text.quality.low : text.quality.good }
}
