import { COACH_INTENTS, createResponsePlan } from './CoachModels.js'
export function planCoachResponse(classification, context, style = {}) {
  if (classification.requiresClarification) return createResponsePlan({ intent: classification.intent, directAnswer: 'I need a little more detail before I can help safely.', followUpQuestion: 'What would you like to review or change?', tone: style.tone, confidence: classification.confidence })
  if (classification.intent === COACH_INTENTS.REPORT_SYMPTOM) return createResponsePlan({ intent: classification.intent, directAnswer: 'Thanks for telling me. Stop or reduce the relevant activity while you assess how you feel.', explanationPoints: ['I cannot diagnose symptoms.', 'Seek urgent care for severe or alarming symptoms; otherwise consider a qualified clinician if symptoms persist.'], warnings: ['Do not use motivation to override pain or illness signals.'], followUpQuestion: 'Are the symptoms severe, sudden, or getting worse?', tone: 'calm', confidence: classification.confidence, sourceDecisions: context.decisions })
  const decision = context.decisions?.[0]
  const actionTypes = { [COACH_INTENTS.LOG_WATER]: 'LOG_WATER', [COACH_INTENTS.LOG_MEAL]: 'CREATE_MEAL_DRAFT', [COACH_INTENTS.ADJUST_GOAL]: 'UPDATE_GOAL_PROPOSAL', [COACH_INTENTS.PLAN_WEEK]: 'CREATE_WEEK_PLAN' }
  const recommendedActions = actionTypes[classification.intent] ? [{ type: actionTypes[classification.intent], payload: { source: 'coach_proposal' } }] : []
  return createResponsePlan({ intent: classification.intent, directAnswer: decision?.recommendation || 'I can help using the current ASKR summaries.', explanationPoints: decision ? [`This is based on the current ${decision.domain || 'ASKR'} decision.`] : ['No current structured decision supports a more specific claim.'], recommendedActions, followUpQuestion: decision ? null : 'Would you like me to prepare a structured proposal?', tone: style.tone, confidence: Math.min(classification.confidence, decision?.confidence ?? .65), sourceDecisions: decision ? [decision] : [] })
}
