import { askrTheme } from './index';

export const sharedComponentStyles = {
  card: {
    background: askrTheme.colors.surface1,
    border: askrTheme.borders.default,
    borderRadius: askrTheme.radius.card,
    boxShadow: 'none',
    color: askrTheme.colors.textPrimary,
    padding: askrTheme.spacing[16],
    transition: `background ${askrTheme.motion.transition.normal}, border-color ${askrTheme.motion.transition.normal}, transform ${askrTheme.motion.transition.normal}`,
    '--askr-card-hover-background': askrTheme.colors.surface2,
  },
  button: {
    primary: {
      background: askrTheme.colors.volt,
      border: '0',
      borderRadius: askrTheme.radius.button,
      color: askrTheme.colors.background,
      fontFamily: askrTheme.typography.body.fontFamily,
      fontWeight: askrTheme.typography.caption.fontWeight,
      minHeight: askrTheme.spacing[48],
      paddingBlock: '0',
      paddingInline: askrTheme.spacing[16],
      transition: `background ${askrTheme.motion.transition.normal}, border-color ${askrTheme.motion.transition.normal}, color ${askrTheme.motion.transition.normal}, transform ${askrTheme.motion.transition.normal}`,
    },
    secondary: {
      background: askrTheme.colors.surface2,
      border: askrTheme.borders.default,
      borderRadius: askrTheme.radius.button,
      color: askrTheme.colors.textPrimary,
      fontFamily: askrTheme.typography.body.fontFamily,
      fontWeight: askrTheme.typography.caption.fontWeight,
      minHeight: askrTheme.spacing[48],
      paddingBlock: '0',
      paddingInline: askrTheme.spacing[16],
      transition: `background ${askrTheme.motion.transition.normal}, border-color ${askrTheme.motion.transition.normal}, color ${askrTheme.motion.transition.normal}, transform ${askrTheme.motion.transition.normal}`,
    },
    ghost: {
      background: 'transparent',
      border: askrTheme.borders.default,
      borderRadius: askrTheme.radius.button,
      color: askrTheme.colors.textPrimary,
      fontFamily: askrTheme.typography.body.fontFamily,
      fontWeight: askrTheme.typography.caption.fontWeight,
      minHeight: askrTheme.spacing[48],
      paddingBlock: '0',
      paddingInline: askrTheme.spacing[16],
      transition: `background ${askrTheme.motion.transition.normal}, border-color ${askrTheme.motion.transition.normal}, color ${askrTheme.motion.transition.normal}, transform ${askrTheme.motion.transition.normal}`,
    },
  },
  badge: {
    base: {
      border: askrTheme.borders.default,
      borderRadius: askrTheme.radius.pill,
      fontFamily: askrTheme.typography.caption.fontFamily,
      fontSize: askrTheme.typography.caption.fontSize,
      fontWeight: askrTheme.typography.caption.fontWeight,
      letterSpacing: askrTheme.typography.caption.letterSpacing,
      paddingBlock: askrTheme.spacing[4],
      paddingInline: askrTheme.spacing[8],
    },
    neutral: { background: askrTheme.colors.surface2, color: askrTheme.colors.textSecondary },
    success: { background: askrTheme.colors.voltDeep, color: askrTheme.colors.volt },
    warning: { background: askrTheme.colors.surface2, color: askrTheme.colors.voltDim },
    danger: { background: askrTheme.colors.surface2, color: askrTheme.colors.textMuted },
  },
  progress: {
    track: {
      background: askrTheme.colors.surface2,
      borderRadius: askrTheme.radius.pill,
      overflow: 'hidden',
      padding: askrTheme.spacing[4],
    },
    indicator: {
      background: askrTheme.colors.volt,
      borderRadius: askrTheme.radius.pill,
      transition: `width ${askrTheme.motion.transition.normal}`,
    },
  },
  progressRing: {
    backgroundTrack: askrTheme.colors.surface2,
    foreground: askrTheme.colors.volt,
    inner: askrTheme.colors.background,
  },
} as const;
