import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowRight, Bell, Bot, Check, ChevronRight, CirclePause, CirclePlay, Dumbbell, Flame, Home, Minus, Plus, Search, Settings, Sparkles, Target, TimerReset, TrendingUp, Trophy, Utensils, X } from 'lucide-react'
import './phase2.css'
import './phase3.css'

import { brandLogoUrl } from './assets'
const nav=[['today','Idag',Home],['train','Träning',Dumbbell],['body','Kropp',Activity],['nutrition','Kost',Utensils],['coach','Coach',Bot]]
const programs=[
 {id:'upper',name:'Överkropp A',focus:'Styrka',duration:58,exercises:[
  {id:'bench',name:'Bänkpress',muscle:'Bröst · Triceps',rest:120,sets:[[72.5,6,8],[72.5,6,8],[72.5,5,9],[70,6,8]]},
  {id:'row',name:'Sittande rodd',muscle:'Rygg · Biceps',rest:90,sets:[[65,8,8],[65,8,8],[65,8,8],[65,7,9]]},
  {id:'press',name:'Axelpress',muscle:'Axlar · Triceps',rest:90,sets:[[24,8,8],[24,8,8],[24,7,9]]},
  {id:'pull',name:'Latsdrag',muscle:'Rygg · Biceps',rest:75,sets:[[60,10,8],[60,10,8],[60,9,9]]}
 ]},
 {id:'lower',name:'Underkropp A',focus:'Kontrollerad styrka',duration:62,exercises:[
  {id:'squat',name:'Knäböj',muscle:'Lår · Säte',rest:150,sets:[[90,6,8],[90,6,8],[87.5,6,8],[87.5,6,8]]},
  {id:'rdl',name:'Raka marklyft',muscle:'Baksida lår · Säte',rest:120,sets:[[80,8,8],[80,8,8],[80,8,9]]},
  {id:'legpress',name:'Benpress',muscle:'Framsida lår',rest:90,sets:[[170,10,8],[170,10,8],[170,10,9]]}
 ]}
]
const seedHistory=[{id:1,date:'18 juli',name:'Överkropp A',duration:56,volume:7820,sets:14},{id:2,date:'15 juli',name:'Underkropp A',duration:63,volume:11240,sets:13},{id:3,date:'12 juli',name:'Överkropp A',duration:54,volume:7510,sets:14}]
const read=()=>{try{return JSON.parse(localStorage.getItem('atlas-phase3')||'null')}catch{return null}}

export default function AppPhase3(){
 const saved=read(); const [page,setPage]=useState(saved?.page||'today'); const [workout,setWorkout]=useState(saved?.workout||null); const [history,setHistory]=useState(saved?.history||seedHistory); const [toast,setToast]=useState(''); const [profile,setProfile]=useState(false)
 useEffect(()=>localStorage.setItem('atlas-phase3',JSON.stringify({page,workout,history})),[page,workout,history])
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2000)}
 const start=p=>{setWorkout({id:Date.now(),name:p.name,elapsed:0,paused:false,exercises:p.exercises.map(e=>({...e,sets:e.sets.map((s,i)=>({id:`${e.id}-${i}`,kg:s[0],reps:s[1],rpe:s[2],done:false}))}))});setPage('train');notify('Passet är startat')}
 const finish=s=>{setHistory([{id:Date.now(),date:'21 juli',...s},...history]);setWorkout(null);notify('Passet sparades')}
 const meta={today:['God morgon, Robert','Din kropp är redo för ett kvalitativt pass.'],train:['Träning','Program, aktivt pass, historik och progression.'],body:['Kroppsstatus','Belastning och återhämtning.'],nutrition:['Kost','Energi, protein och vanor.'],coach:['ATLAS Coach','Råd grundade i din träningsdata.']}[page]
 return <div className="app-shell"><aside className="sidebar"><Brand/><nav className="desktop-nav">{nav.map(([id,label,Icon])=><Nav key={id} id={id} label={label} Icon={Icon} active={page===id} setPage={setPage}/>)}</nav><div className="sidebar-footer"><button className="profile-card" onClick={()=>setProfile(!profile)}><span className="avatar">RE</span><span><strong>Robert</strong><small>ATLAS Member</small></span><Settings size={17}/></button></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">Tisdag · 21 juli</p><h1>{meta[0]}</h1><p>{meta[1]}</p></div><div className="topbar-actions"><button className="icon-button"><Search size={19}/></button><button className="icon-button notification"><Bell size={19}/><span/></button></div></header><section className="page-stage">{page==='today'&&<Today start={start} setPage={setPage}/>} {page==='train'&&<Training workout={workout} setWorkout={setWorkout} start={start} finish={finish} history={history} notify={notify}/>} {page==='body'&&<Body/>} {page==='nutrition'&&<Placeholder icon={Utensils} title="Kostloggen" text="Kostmodulen från fas 1 ligger kvar och kopplas senare till samma datalager."/>} {page==='coach'&&<Placeholder icon={Bot} title="ATLAS Coach" text="Coachen kommer att använda loggade set, RPE, progression och återhämtning."/>}</section></main><nav className="mobile-nav">{nav.map(([id,label,Icon])=><Nav key={id} id={id} label={label} Icon={Icon} active={page===id} setPage={setPage} compact/>)}</nav>{profile&&<div className="profile-popover"><strong>Robert Ekholm</strong><span>Pass sparas lokalt i webbläsaren.</span></div>}{toast&&<div className="toast">{toast}</div>}</div>
}
function Brand(){return <div className="brand"><img className="brand-logo" src={brandLogoUrl} alt="ASKR"/></div>}
function Nav({id,label,Icon,active,setPage,compact}){return <button className={`nav-button ${active?'active':''} ${compact?'compact':''}`} onClick={()=>setPage(id)}><Icon size={20}/><span>{label}</span></button>}
function Today({start,setPage}){return <div className="dashboard-grid"><section className="hero-card span-8"><div><span className="status-pill"><Sparkles size={15}/> Dagens rekommendation</span><h2>Överkropp · styrka</h2><p>Återhämtningen är stabil. Håll två repetitioner i reserv på de tyngsta seten.</p><div className="hero-actions"><button className="primary-button" onClick={()=>start(programs[0])}><Dumbbell size={18}/> Starta pass</button><button className="text-button" onClick={()=>setPage('train')}>Visa program <ArrowRight size={17}/></button></div></div><div className="readiness-ring"><span>82</span><small>Redo</small></div></section><Card icon={Activity} label="Återhämtning" value="82%" note="Optimal träningsdag"/><Card icon={Flame} label="Veckobelastning" value="68%" note="Inom optimal zon"/><Card icon={TrendingUp} label="Progression" value="+3,4%" note="Senaste 4 veckorna"/><Card icon={Target} label="Veckomål" value="2 / 4" note="Två pass kvar"/></div>}
function Training({workout,setWorkout,start,finish,history,notify}){const [tab,setTab]=useState(workout?'active':'plan');useEffect(()=>{if(workout)setTab('active')},[workout]);return <div className="training-engine"><div className="training-tabs">{[['plan','Program'],['active','Aktivt pass'],['history','Historik'],['progress','Progression']].map(([id,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{l}{id==='active'&&workout&&<i/>}</button>)}</div>{tab==='plan'&&<Programs start={start}/>} {tab==='active'&&(workout?<Active workout={workout} setWorkout={setWorkout} finish={finish} notify={notify}/>:<Empty start={()=>start(programs[0])}/>)} {tab==='history'&&<History history={history}/>} {tab==='progress'&&<Progress/>}</div>}
function Programs({start}){const [id,setId]=useState('upper');const p=programs.find(x=>x.id===id);return <div className="phase3-grid"><section className="panel program-picker span-4"><Heading eyebrow="Mina program" title="Veckoupplägg"/><div className="program-list">{programs.map(x=><button key={x.id} className={id===x.id?'selected':''} onClick={()=>setId(x.id)}><span><strong>{x.name}</strong><small>{x.focus} · {x.duration} min</small></span><ChevronRight size={18}/></button>)}</div></section><section className="hero-card phase3-hero span-8"><div><span className="status-pill"><Sparkles size={15}/> Rekommenderat idag</span><h2>{p.name}</h2><p>{p.focus} · {p.duration} minuter · {p.exercises.reduce((n,e)=>n+e.sets.length,0)} arbetsset</p><button className="primary-button" onClick={()=>start(p)}><CirclePlay size={18}/> Starta pass</button></div><TimerReset size={90}/></section><section className="panel span-12"><Heading eyebrow="Passinnehåll" title="Övningar"/><div className="program-exercises">{p.exercises.map((e,i)=><div key={e.id}><span className="exercise-index">{i+1}</span><span><strong>{e.name}</strong><small>{e.muscle}</small></span><b>{e.sets.length} set</b></div>)}</div></section></div>}
function Active({workout,setWorkout,finish,notify}){const [rest,setRest]=useState(0);const [modal,setModal]=useState(false);useEffect(()=>{if(workout.paused)return;const i=setInterval(()=>setWorkout(w=>({...w,elapsed:w.elapsed+1})),1000);return()=>clearInterval(i)},[workout.paused,setWorkout]);useEffect(()=>{if(rest<=0)return;const i=setInterval(()=>setRest(r=>r-1),1000);return()=>clearInterval(i)},[rest]);const sets=workout.exercises.flatMap(e=>e.sets),done=sets.filter(s=>s.done).length,total=sets.length,volume=sets.filter(s=>s.done).reduce((n,s)=>n+s.kg*s.reps,0);const patch=(ei,si,p)=>setWorkout(w=>({...w,exercises:w.exercises.map((e,x)=>x!==ei?e:{...e,sets:e.sets.map((s,y)=>y!==si?s:{...s,...p})})}));const toggle=(ei,si,r)=>{const s=workout.exercises[ei].sets[si];patch(ei,si,{done:!s.done});if(!s.done){setRest(r);notify('Set loggat · vilotimer startad')}};return <div className="active-workout"><section className="workout-command panel"><div><span className="status-pill"><Flame size={15}/> Aktivt pass</span><h2>{workout.name}</h2><p>{done} av {total} set · {Math.round(volume).toLocaleString('sv-SE')} kg</p></div><div className="session-clock"><strong>{time(workout.elapsed)}</strong><button onClick={()=>setWorkout(w=>({...w,paused:!w.paused}))}>{workout.paused?<CirclePlay/>:<CirclePause/>}</button></div></section>{rest>0&&<section className="rest-banner"><TimerReset/><span>Vila</span><strong>{time(rest)}</strong><button onClick={()=>setRest(0)}>Hoppa över</button></section>}<div className="workout-progress"><div><span style={{width:`${done/total*100}%`}}/></div><b>{Math.round(done/total*100)}%</b></div><div className="active-exercises">{workout.exercises.map((e,ei)=><Logger key={e.id} e={e} ei={ei} patch={patch} toggle={toggle}/>)}</div><section className="finish-bar panel"><div><strong>{done}/{total} set</strong><span>{Math.round(volume).toLocaleString('sv-SE')} kg volym</span></div><button className="primary-button" disabled={!done} onClick={()=>setModal(true)}><Check size={18}/> Avsluta pass</button></section>{modal&&<div className="modal-backdrop"><div className="finish-modal"><button className="modal-close" onClick={()=>setModal(false)}><X/></button><Trophy size={42}/><h3>Spara träningspass?</h3><p>{done} set · {Math.round(volume).toLocaleString('sv-SE')} kg · {time(workout.elapsed)}</p><button className="primary-button full" onClick={()=>finish({name:workout.name,duration:Math.max(1,Math.round(workout.elapsed/60)),volume:Math.round(volume),sets:done})}>Spara och avsluta</button></div></div>}</div>}
function Logger({e,ei,patch,toggle}){const [open,setOpen]=useState(true),done=e.sets.filter(s=>s.done).length;return <section className={`panel exercise-logger ${done===e.sets.length?'complete':''}`}><button className="exercise-logger-head" onClick={()=>setOpen(!open)}><span><strong>{e.name}</strong><small>{e.muscle}</small></span><span className="set-progress">{done}/{e.sets.length}</span><ChevronRight/></button>{open&&<div className="set-table"><div className="set-row set-head"><span>Set</span><span>Kg</span><span>Reps</span><span>RPE</span><span>Klar</span></div>{e.sets.map((s,si)=><div className={`set-row ${s.done?'done':''}`} key={s.id}><span>{si+1}</span><Step value={s.kg} step={2.5} set={v=>patch(ei,si,{kg:v})}/><Step value={s.reps} step={1} set={v=>patch(ei,si,{reps:v})}/><select value={s.rpe} onChange={x=>patch(ei,si,{rpe:Number(x.target.value)})}>{[6,7,8,9,10].map(v=><option key={v}>{v}</option>)}</select><button className="set-check" onClick={()=>toggle(ei,si,e.rest)}>{s.done?<Check size={18}/>:<span/>}</button></div>)}</div>}</section>}
function Step({value,step,set}){return <div className="number-stepper"><button onClick={()=>set(Math.max(0,Number((value-step).toFixed(1))))}><Minus size={13}/></button><input value={value} onChange={e=>set(Number(e.target.value)||0)}/><button onClick={()=>set(Number((value+step).toFixed(1)))}><Plus size={13}/></button></div>}
function History({history}){return <div className="phase3-grid"><section className="panel span-8"><Heading eyebrow="Sparade pass" title="Träningshistorik"/><div className="history-list">{history.map(h=><div key={h.id}><span className="history-icon"><Dumbbell/></span><span><strong>{h.name}</strong><small>{h.date} · {h.duration} min · {h.sets} set</small></span><b>{h.volume.toLocaleString('sv-SE')} kg</b></div>)}</div></section><section className="panel span-4"><Heading eyebrow="30 dagar" title="Summering"/><div className="history-stats"><Mini value={history.length} label="Pass"/><Mini value={`${history.reduce((n,h)=>n+h.duration,0)} min`} label="Tid"/><Mini value={`${Math.round(history.reduce((n,h)=>n+h.volume,0)/1000)} t`} label="Volym"/></div></section></div>}
function Progress(){const bars=[62,66,65,70,72.5,72.5,75];return <div className="phase3-grid"><section className="panel span-8"><Heading eyebrow="Bänkpress" title="Styrkeutveckling"/><div className="progress-chart">{bars.map((v,i)=><div key={i}><b>{v}</b><span style={{height:`${v/80*100}%`}}/><small>V{i+1}</small></div>)}</div></section><section className="panel span-4"><Heading eyebrow="Personbästa" title="Senaste framsteg"/><div className="pr-card"><Trophy/><strong>75 kg × 6</strong><span>Beräknat 1RM: 90 kg</span></div></section></div>}
function Empty({start}){return <section className="panel empty-workout"><div className="coach-orb"><Dumbbell/></div><h2>Inget aktivt pass</h2><p>Starta programmet och logga varje set under träningen.</p><button className="primary-button" onClick={start}><CirclePlay/> Starta Överkropp A</button></section>}
function Body(){return <div className="body-dashboard"><section className="panel body-command"><div><span className="status-pill"><Activity size={15}/> Levande kroppskarta</span><h2>Kroppen styr nästa beslut</h2><p>Bröst och armar är redo. Ländrygg och vader behöver återhämtning.</p></div><div className="body-summary"><Summary value="8" label="Redo" tone="ready"/><Summary value="6" label="Belastade" tone="loaded"/><Summary value="3" label="Vila" tone="attention"/></div></section><section className="panel anatomy-panel body-placeholder"><div className="body-mini"><span/><i className="chest"/><i className="legs"/></div></section></div>}
function Placeholder({icon:Icon,title,text}){return <section className="panel empty-workout"><div className="coach-orb"><Icon size={38}/></div><h2>{title}</h2><p>{text}</p></section>}
function Card({icon:Icon,label,value,note}){return <article className="metric-card span-4"><div className="metric-icon"><Icon/></div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Heading({eyebrow,title}){return <div className="section-heading"><div><span>{eyebrow}</span><h3>{title}</h3></div></div>}
function Mini({value,label}){return <div className="metric-mini"><strong>{value}</strong><span>{label}</span></div>}
function Summary({value,label,tone}){return <div className={`summary-stat ${tone}`}><strong>{value}</strong><span>{label}</span></div>}
function time(s){return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`}
