export const VALID_HOME_PAGES = new Set(['today', 'coach', 'goal', 'recovery', 'decisions', 'settings'])
export const atlasHomeTokens = { background: '#030504', surface: '#0b1411', surfaceRaised: '#111d18', text: '#f4faf7', muted: '#8ea19a', lime: '#b8ff46', warning: '#ff9f43', danger: '#ff5f57', radius: '22px', shadow: '0 22px 60px rgba(0,0,0,.42)', duration: '180ms' }
function isReal(value) { return value !== undefined && value !== null && !(typeof value === 'number' && Number.isNaN(value)) && value !== '' }
function number(value) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : null }
function pct(value) { const parsed = number(value); return parsed === null ? null : `${Math.round(parsed)}%` }
function firstName(profile = {}, recommendation = {}) { return String(recommendation.context?.firstName || profile.firstName || profile.name || '').trim().split(/\s+/)[0] || 'du' }
function greeting(date = new Date()) { const hour = date.getHours(); if (hour < 10) return 'God morgon'; if (hour < 17) return 'Hej'; return 'God kväll' }
export function safeHomeTarget(target, fallback = 'today') { return VALID_HOME_PAGES.has(target) ? target : fallback }
function newest(workouts = []) { return [...workouts].sort((a,b) => new Date(b.completedAt || b.date || 0) - new Date(a.completedAt || a.date || 0))[0] || null }
export function buildHomeViewModel({ profile = {}, core = {}, recommendation = {}, readiness, now = new Date() }) {
  const checkIn = profile.checkIn || {}
  const latest = recommendation.context?.latestWorkout || profile.coreSummary?.latestWorkout || newest(core.workouts)
  const weeklyCompletion = number(recommendation.context?.weeklyCompletion ?? profile.coreSummary?.recentWorkoutCount)
  const weeklyTarget = number(profile.goal?.weeklySessions || profile.goal?.sessionsPerWeek || core.goalPlans?.active?.weeklySessions || 4)
  const recoveryScore = number(recommendation.context?.recoveryScore ?? profile.recovery?.total ?? readiness ?? core.recovery?.score)
  const status = recommendation.insufficientData ? 'Logga dagsform och pass för mer personlig precision.' : (recommendation.summary || 'ATLAS väger samman återhämtning, mål och träningshistorik inför dagens val.')
  const metrics = [recoveryScore !== null && { id: 'recovery', label: 'Återhämtning', value: pct(recoveryScore), note: recoveryScore >= 70 ? 'Redo för kvalitet' : 'Hantera belastning' }, isReal(checkIn.sleep) && { id: 'sleep', label: 'Sömn', value: `${checkIn.sleep} h`, note: 'Senaste check-in' }, isReal(checkIn.energy) && { id: 'energy', label: 'Energi', value: `${checkIn.energy}/10`, note: 'Egen skattning' }, isReal(checkIn.motivation) && { id: 'motivation', label: 'Motivation', value: `${checkIn.motivation}/10`, note: 'Egen skattning' }, weeklyCompletion !== null && { id: 'week', label: 'Veckan', value: `${weeklyCompletion}/${weeklyTarget || '–'}`, note: 'Pass senaste 7 dagarna' }].filter(Boolean)
  const muscles = Object.entries(core.recovery?.muscles || {}).map(([name, value]) => ({ name, readiness: Math.max(0, Math.round(100 - Number(value?.fatigue || 0))) })).sort((a, b) => a.readiness - b.readiness).slice(0, 4)
  return { greeting: `${greeting(now)}, ${firstName(profile, recommendation)}`, status, headline: recommendation.headline || 'ATLAS behöver mer underlag.', explanation: recommendation.summary || status, confidence: recommendation.dataQuality ? `${recommendation.confidenceLabel || 'okänd'} säkerhet · ${recommendation.dataQuality.label} datakvalitet (${recommendation.dataQuality.signals}/${recommendation.dataQuality.possibleSignals} signaler)` : `${Math.round(Number(recommendation.confidence || 0) * 100)}% säkerhet`, primaryLabel: recommendation.primaryActionLabel || 'ÖPPNA COACH', primaryTarget: safeHomeTarget(recommendation.primaryActionTarget, 'coach'), secondary: recommendation.alternatives?.[0] ? { label: recommendation.alternatives[0].label, target: safeHomeTarget(recommendation.alternatives[0].target, 'coach') } : null, metrics, muscles, latest, weeklyCompletion, weeklyTarget, workoutName: recommendation.decision?.title || recommendation.headline || 'Dagens pass', workoutNote: recommendation.decision?.message || recommendation.summary || 'Öppna planen för säkert nästa steg.', workoutTarget: safeHomeTarget(recommendation?.primaryActionTarget, 'goal'), insufficient: Boolean(recommendation.insufficientData) }
}
